vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    technology_image:
      uri_prefix: /images/technologies
      upload_destination: '%kernel.project_dir%/public/images/technologies'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer